apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: slack-clone
  labels:
    app: frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
