apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    tier: backend
    {{- include "slack-clone.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
