apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slack-clone.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: "mongodb://{{ .Values.mongo.auth.username }}:{{ .Values.mongo.auth.password }}@mongo.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ .Values.mongo.auth.database }}?authSource=admin"
