apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slack-clone.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  REDIS_URL: "redis://redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
