apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slack-clone.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.auth.password | quote }}
